### ISSUE TITLE
Boom.wrap discards message when error isBoom

### ISSUE THREAD

**Issue by karlkfi** [hapijs/boom#100]
Why does Boom.wrap do nothing if the error/cause is a boom error? Shouldn't it wrap it and just overwrite the status code? I wouldn't expect the new status code and message to be dropped on the floor...

https://github.com/hapijs/boom/blob/master/lib/index.js#L76

**Comment by hueniverse** [comment]
It's just how it's used within the hapi ecosystem.

**Comment by arb** [comment]
If you already have a boom object in hand, why are you calling `Boom.wrap` again on it? Can't you just overwrite the values you want or create a new Boom object?

**Comment by hueniverse** [comment]
wrap() only converts if it is not already a boom error. Just how it works.
