### ISSUE TITLE
Using `instanceof` operator to distinguish between Boom errors

### ISSUE THREAD

**Issue by mmiszy** [hapijs/boom#101]
I'm not sure whether it's a design choice or a side-effect of current implementation but `instanceof` operator cannot be used to detect Boom errors.

### Current behaviour:

``` javascript
const notFound = new Boom.notFound();
notFound instanceof Boom.notFound // false
```

### Suggested behaviour:
I expected this would yield `true` :) Moreover I think the desired behaviour can be described with the following spec:

``` javascript
const notFound = new Boom.notFound();
const notImplemented = new Boom.notImplemented();
notFound instanceof Boom.notFound // true
notImplemented instanceof Boom.notImplemented // true
notFound instanceof Boom.notImplemented // false
```

### Justification:
Many libraries try to distinguish objects using the `instanceof` operator. The one I'm particularly interested in is Bluebird – Promise library. Its `catch` function has a very nice extension which makes working with exceptions much easier:
> This is an extension to .catch to work more like catch-clauses in languages like Java or C#. Instead of manually checking instanceof or .name === "SomeError", you may specify a number of error constructors which are eligible for this catch handler.

If the suggested change to Boom is implemented example code could look like this:
```javascript
mayThrowBoomError()
    .then(result => …)
    .catch(Boom.notFound, err => …)
    .catch(Boom.forbidden, err => …)
    .catch(err => …)
```
which is much more convenient than catching the error and adding a `switch` clause over the `err.content.statusCode`

So the question is whether this is an architectural choice or rather a side-effect, and is there any reason against implementing this in Boom?

**Comment by devinivy** [comment]
I wont speak to this design choice, but boom objects can be detected using `error.isBoom`.

**Comment by JakubJagoda** [comment]
@devinivy But that won't tell you quickly what _type_ of error it is (you would need to check the code as well). That's useful in hapi routes, when you can reply different things, basing on what actually happened. And it actually goes well with bluebird, as shown in the example.

**Comment by hueniverse** [comment]
boom errors are just `Error`. We don't have a type per code. In many cases, boom only decorates an existing error object, not creating a new one.

**Comment by mmiszy** [comment]
That's why I suggest it should have a type per code and it should inherit from Error (then `instanceof Error` will still hold true). Would that interfere with anything?

**Comment by hueniverse** [comment]
It will. We pass errors as-is and just add some properties to them when you call wrap. Can't do that without a deep clone under your proposal. I also don't really find the pattern above to be that useful to justify creating dozens of new prototypes.

**Comment by arb** [comment]
I agree, that seems like a lot of overhead just to accommodate this feature.

**Comment by Marsup** [comment]
To add a more pragmatic pov, I recently tried to do that in joi, creating custom errors that keep the properties of errors (stack, ...) is such a horrible mess I'm never ever doing that again. It's doable in pure V8, but good luck with other engines, we're hostile enough as it is for browser-land not to add that to our plate.
