### ISSUE TITLE
const declarations aren't allowed in Safari strict mode.

### ISSUE THREAD

**Issue by nicholaswyoung** [hapijs/boom#102]
`const` declarations are not allowed when running with `use strict` in the latest Safari (9.0.2) via Browserify.

https://github.com/hapijs/boom/blob/master/lib/index.js#L5

While I can compile this error away, some people might rather have a transpiled ES5 version for now, perhaps distributed via the `browser` key in `package.json`?

**Comment by arb** [comment]
`const` not being allowing with "use strict" does not make a single lick of sense...

That being said, this module really doesn't make much sense on the client and I have no plans to support or distribute a client friendly version. Your best bet would be to use webpack or browserify like you suggested and transpile this down to es5.

**Comment by nicholaswyoung** [comment]
I don't know why the error occurs, but it does. I mostly brought this to your attention as additional information, for use if it was helpful — a stone discarded if it wasn't. 

I'll close this now, since most use cases for Boom are server side only.
