### ISSUE TITLE
Cannot use 3xx error codes

### ISSUE THREAD

**Issue by scmorse** [hapijs/boom#103]
Even the custom `.create` method does not allow using a 300 level error code. 

Why does Boom not support 300 level status codes?

**Comment by devinivy** [comment]
Boom is specifically used for expressing HTTP errors, and codes in the 3xx range are not considered errors.  HTTP errors are in the 4xx and 5xx ranges.

**Comment by scmorse** [comment]
Is there another package for creating responses for 3xx level codes? I'm just looking for an easy way to throw an object that tells hapi that it should be a redirect. The way the code is modularized, the `reply` object is not available, so doing `reply.redirect(...)` isn't an option.

**Comment by devinivy** [comment]
Yes– at least if you have access to the `request`.  Check out [`request.generateResponse()`](https://github.com/hapijs/hapi/blob/master/API.md#requestgenerateresponsesource-options).

**Comment by hueniverse** [comment]
You don't throw a redirect.
