### ISSUE TITLE
Error when running uglify 

### ISSUE THREAD

**Issue by Gattermeier** [hapijs/boom#104]
we are using webpack.optimize.UglifyJsPlugin for optimization. 
However it throws an error with Boom: 

> stream.js:74
>       throw er; // Unhandled stream error in pipe.
>       ^
> Error: app.js from UglifyJs
> Unexpected token: name (wwwAuthenticate) [./~/boom/lib/index.js:161,0]

**Comment by Marsup** [comment]
That's probably because uglify doesn't understand ES6, you need to transpile it first.

**Comment by Gattermeier** [comment]
Correct. Works when first transpiling with Babel. Thanks @Marsup
