### ISSUE TITLE
[Boom.wrap(err)] check if err is a real error instance

### ISSUE THREAD

**Issue by ms88privat** [hapijs/boom#107]
I'm testing hapijs and boom for the first time and got stuck for over an hour by this issue. 

I realized, that one of my plugins only returned some object as an "error" instead of an error instance. The result was, that my reply with Boom.wrap(err) didn't resolve at all and no other error message was thrown in my console.

Would it be a good idea to implement an "instanceof Error check" in Boom.wrap? I think this problem could be very common and it has very bad consequences for the users.

Anyways, awesome plugin so far 👍

**Comment by arb** [comment]
There already is an instance of check [here](https://github.com/hapijs/boom/blob/master/lib/index.js#L73-L77). Not sure what issue you were having.

**Comment by ms88privat** [comment]
@arb I'm sorry, I should have looked for myself. I resolved my issue, it was related to await/async ES7.
