### ISSUE TITLE
Boom error using node 6

### ISSUE THREAD

**Issue by roderik** [hapijs/boom#109]
Using node 6 I run into this error:
```
nodeapi_1              |     TypeError: Cannot set property message of Error which has only a getter
nodeapi_1              |     at Object.internals.initialize (/usr/src/app/node_modules/hapi/node_modules/boom/lib/index.js:124:23)
nodeapi_1              |     at Object.exports.wrap (/usr/src/app/node_modules/hapi/node_modules/boom/lib/index.js:76:46)
nodeapi_1              |     at Object.internals.serverError (/usr/src/app/node_modules/hapi/node_modules/boom/lib/index.js:349:25)
nodeapi_1              |     at Object.exports.badImplementation (/usr/src/app/node_modules/hapi/node_modules/boom/lib/index.js:386:27)
nodeapi_1              |     at _error (/usr/src/app/node_modules/hapi/lib/protect.js:61:28)
nodeapi_1              |     at internals.Protect._onError (/usr/src/app/node_modules/hapi/lib/protect.js:40:16)
nodeapi_1              |     at Domain.domain.on (/usr/src/app/node_modules/hapi/lib/protect.js:30:21)
nodeapi_1              |     at emitOne (events.js:96:13)
nodeapi_1              |     at Domain.emit (events.js:188:7)
nodeapi_1              |     at Domain.errorHandler [as _errorHandler] (domain.js:113:21)
```

due to https://github.com/hapijs/boom/blob/master/lib/index.js#L124 and the changes in node 6

**Comment by arb** [comment]
Doesn't seem to have anything to do with Node 6. Changing how `Error` works would be a massive change; doubt they would make that sweeping of a change. Also, the travis run on Node 6 works fine.

**Comment by teemuniiranen** [comment]
I have same sort of problem but in case of ECONNRESET:
```
stack:
'TypeError: Cannot set property message of  which has only a getter',
'    at Object.internals.initialize (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:124:23)',
'    at Object.exports.wrap (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:76:46)',
'    at Object.internals.serverError (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:371:25)',
'    at Object.exports.badImplementation (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:408:27)',
'    at _error (/data/app/node_modules/hapi/lib/protect.js:55:32)',
'    at module.exports.internals.Protect.internals.Protect._onError (/data/app/node_modules/hapi/lib/protect.js:37:16)',
'    at emitOne (events.js:96:13)',
'    at Domain.emit (events.js:191:7)',
'    at EventEmitter.emit (events.js:161:14)',
'    at sendResult (/data/app/node_modules/ldapjs/lib/client/client.js:1389:22)',
'    at messageCallback (/data/app/node_modules/ldapjs/lib/client/client.js:1423:16)',
'    at /data/app/node_modules/ldapjs/lib/client/client.js:1277:14',
'    at Array.forEach (native)',
'    at Client._onClose (/data/app/node_modules/ldapjs/lib/client/client.js:1272:19)',
'    at Object.onceWrapper (events.js:293:19)',
'    at emitOne (events.js:96:13)',
'    at Socket.emit (events.js:191:7)',
'    at TCP._handle.close [as _onclose] (net.js:511:12)' ] }
```

Is this because of Boom version (4.1.0) or why? Code that causes the problem:
```
if (message) {
        error.message = (message + (error.message ? ': ' + error.message : ''));
}
```

**Comment by tuohaibei** [comment]
> I have same sort of problem but in case of ECONNRESET from LDAP client:
> 
> ```
> stack:
> 'TypeError: Cannot set property message of  which has only a getter',
> '    at Object.internals.initialize (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:124:23)',
> '    at Object.exports.wrap (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:76:46)',
> '    at Object.internals.serverError (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:371:25)',
> '    at Object.exports.badImplementation (/data/app/node_modules/hapi/node_modules/boom/lib/index.js:408:27)',
> '    at _error (/data/app/node_modules/hapi/lib/protect.js:55:32)',
> '    at module.exports.internals.Protect.internals.Protect._onError (/data/app/node_modules/hapi/lib/protect.js:37:16)',
> '    at emitOne (events.js:96:13)',
> '    at Domain.emit (events.js:191:7)',
> '    at EventEmitter.emit (events.js:161:14)',
> '    at sendResult (/data/app/node_modules/ldapjs/lib/client/client.js:1389:22)',
> '    at messageCallback (/data/app/node_modules/ldapjs/lib/client/client.js:1423:16)',
> '    at /data/app/node_modules/ldapjs/lib/client/client.js:1277:14',
> '    at Array.forEach (native)',
> '    at Client._onClose (/data/app/node_modules/ldapjs/lib/client/client.js:1272:19)',
> '    at Object.onceWrapper (events.js:293:19)',
> '    at emitOne (events.js:96:13)',
> '    at Socket.emit (events.js:191:7)',
> '    at TCP._handle.close [as _onclose] (net.js:511:12)' ] }
> ```
> Is this because of Boom version (4.1.0) and is it fixed on later releases? Code that causes the problem:
> 
> ```
> if (message) {
>         error.message = (message + (error.message ? ': ' + error.message : ''));
> }
> ```

I have the same iisue,how can i fix it?
