### ISSUE TITLE
HTTP Error 423 (Locked)

### ISSUE THREAD

**Issue by jsonmaur** [hapijs/boom#111]
I use the error code 423 (Locked) to let users know if their account or an associated resource has been temporarily locked by an admin. I'm using 403 (Forbidden) in place of it right now, but I'm curious as to whether this was left out intentionally because it is for WebDAV in the official spec? I'd be happy to submit a PR if you agree it's appropriate for this use case. No worries if not.

**Comment by arb** [comment]
I just look at what the `http` module includes as far as status codes. If it's in that list, that's good enough for me. I'd take a PR to add this.

**Comment by arb** [comment]
Closed via c3b3c6b8137d719c9afcb890020a5c55c3d3a0c5
