### ISSUE TITLE
Allow creation of 3xx Redirection objects

### ISSUE THREAD

**Issue by zatziky** [hapijs/boom#114]
I know Boom is meant for 4xx and 5xx statuses only. On the second thought other status codes may also be handled as error states. For example 301 "Moved Permanently" and 302 "Moved Temporarily" can be handled by an error middleware too. 

The new factory method could look like this:

`Boom.redirectPermanently(url, [message], [data])`

What do you say?

**Comment by hueniverse** [comment]
Nope. Only 4xx and 5xx are errors. It makes no sense to treat 3xx as errors.

**Comment by zatziky** [comment]
@hueniverse What about 305 "Use Proxy"? But anyways we are using the Boom project on ExpressJs not with Happi. Maybe in Happi it really doesn't make sense.

**Comment by hueniverse** [comment]
boom is designed exclusively for hapi. It is a core piece of the ecosystem.
