### ISSUE TITLE
Is there a way to log all Errors?

### ISSUE THREAD

**Issue by Vadorequest** [hapijs/boom#124]
It becomes hard to debug sometimes because of `Boom.wrap`:
>All 500 errors hide your message from the end user. Your message is recorded in the server log.

For instance:
```
myFunc: ->
  d = q.defer()
  d.reject "I'm crashing here!" // Replace this by `d.reject new Error "I'm crashing here!"` and it's gonna work.
  return d.promise

myFunc().catch (err) -> Boom.wrap err
```
_This does not work. But it should. (because otherwise it's a pain to debug)_ 

What we are looking for is a way to print every single error, whether there are 5xx errors, or reject, etc. **But only in dev mode**. So, is there a way to setup Boom in such a way? Maybe some config to add ourselves when not in production mode?

**Comment by arb** [comment]
Boom doesn't log anything, it's just a helper utility for creating structured HTTP error objects. If you're looking to log this from your server, there are many logging frameworks available to you. Bunyan, winston, good... there are probably over 2 dozen logging frameworks to choose from.
