### ISSUE TITLE
Cannot send args using Boom.badRequest

### ISSUE THREAD

**Issue by Vadorequest** [hapijs/boom#126]
I'm trying to send back a message and additional data to the fronten,d in my route.

```coffeescript
return reply Boom.badRequest('Required fields are missing', {validation: {source: 'payload', keys: _missingFields}})
```

But I only get `{"statusCode":400,"error":"Bad Request","message":"Required fields are missing"}` without the additional data. I don't know why, isn't it supposed to work out of the box? Any idea?
I'm using Boom 4.0.0. I updated from 2.8 wondering if it wasn't the reason, but it doesn't seem so.

**Comment by arb** [comment]
Have you read https://github.com/hapijs/boom#faq yet? Sounds similar to that kind of question.

**Comment by Vadorequest** [comment]
```
_missingFields = _.xor(_mandatoryFields, _.pluck(_userMandatoryFields, 'label'))
error = Boom.badRequest 'Required fields are missing'
error.output.payload.validation =
source: 'payload'
keys: _missingFields
error.reformat() # XXX https://github.com/hapijs/hapi/blob/master/API.md#error-transformation
return reply error
```

It works this way, thanks. I just wonder if there isn't a more straight-forward way to do it.
Thank you! :)
