### ISSUE TITLE
Boom.internal not in API docs

### ISSUE THREAD

**Issue by tribou** [hapijs/boom#127]
I noticed `Boom.internal()` isn't listed in the README API. Is this deprecated, or should it be added to the docs?

**Comment by arb** [comment]
Go for it.

**Comment by rohit103** [comment]
Hi @arb can you please check. I am not able to find documentation for Boom.internal(err) still in the official docs: https://www.npmjs.com/package/boom Am I looking at the wrong place?

**Comment by arb** [comment]
https://github.com/hapijs/boom#boombadimplementationmessage-data---alias-internal
