### ISSUE TITLE
Boom Response 

### ISSUE THREAD

**Issue by Kamaraju333** [hapijs/boom#131]
Can i Customize the keys in the payload from statusCode to status or message to errorMessage?

**Comment by arb** [comment]
Yes. What context are you using boom? With hapi or with something else?

**Comment by Kamaraju333** [comment]
Hi ,

I am using for handling error message in my node project , am using boom
directly.

Thanks
Kamaraju

**Comment by arb** [comment]
The boom result is just a JS object, you can assign any key and any value to it before using it. I'm not sure I understand the scope of your question.

**Comment by Kamaraju333** [comment]
If i use Boom like below 
throw Boom.notFound("User Not Found")
it Gives me the error is a specific structure , Can i customize it so that it returns me only in a specific Format .

**Comment by arb** [comment]
Yes 
```js
const err = Boom.notFound('User Not Found')`;
err.status = err.statusCode;
err.errorMessage = err.message
throw err;
```

It's JavaScript, you can do whatever you want to the object after it's constructed.
