### ISSUE TITLE
Hapi Server becomes unresponsive after second call

### ISSUE THREAD

**Issue by cjduncana** [hapijs/boom#140]
I recently started a new project and since I have used Hapi before and was happy with it, I used it again.

I have everything modularized, nice and pretty. The project includes a handlers folder with files that each contains handlers for the same resource. For example, in the same file, I would have a handler to get a resource by its ID and another one that would update a resource by its ID. Since I want handlers of the same resource to return the same errors (in the previous example, an example would be a `Boom.notFound('Resource was not found');`), I store them in a `const` and use the `const` where needed.

In my previous project, this gave me no issue, but it does now. The issue is that the server becomes unresponsive after the second call. Trying to find the source of the problem, I came up with the following code that reproduces the issue:

```js
'use strict';

const Boom = require('boom');
const Hapi = require('hapi');

const ERROR_TEST = Boom.forbidden('Error Test');

const server = new Hapi.Server();
server.connection({ port: 3000 });

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {
        reply(ERROR_TEST);
    }
});

server.start((err) => {

    if (err) {
        throw err;
    }
    console.log(`Server running at: ${server.info.uri}`);
});
```

With this code, I call the server and I get an error response, as expected. If I call it again, there's no response from the server. If I call it a third time, there's no response from the server. All subsequent calls return no response.

If I replace the `const` for its value, everything works, so I have been changing my code accordingly, but I know that in the previous project the server worked without the replacement. This indicates me that there was a bug introduced in later versions of either hapi or more likely, boom.

The problem is not solely with `Boom.forbidden()`. I have tried the same code with `Boom.badRequest()`, `Boom.unauthorized()`, `Boom.paymentRequired()`, and `Boom.notFound()`. I'm guessing that the other errors will behave similarly.

### Old Project

* *node version*: v6.0.0
* *hapi version*: ^13.5.0
* *boom version*: ^3.2.1
* *os*: Debian Jessie
Inside a Docker Container

### New Project

* *node version*: v6.0.0
* *hapi version*: ^15.0.3
* *boom version*: ^4.0.0
* *os*: Debian Jessie
Inside a Docker Container

### Test Code in this issue

* *node version*: v6.0.0
* *hapi version*: ^15.2.0
* *boom version*: ^4.2.0
* *os*: OS X El Capitán
Outside a Docker Container

**Comment by hueniverse** [comment]
This is unlikely to be a boom issue. You should open it in hapi.

**Comment by wwalser** [comment]
I have the same behavior with Hapi 13.5.3 & Boom 3.2.2. Doesn't seem like a reason change, seems like something gets mutated on the Boom object by Hapi that doesn't allow them to be reused for multiple requests. For now I'm getting around it with:

```javascript
    const myError = ()=>Boom.badRequest(…);
```

I'll go ahead and re-create this issue over on Hapi's project.

**Comment by wwalser** [comment]
Opened here: https://github.com/hapijs/hapi/issues/3378

**Comment by arb** [comment]
Per your investigation, it's very likely hapi is doing some kind of mutation that is causing this issue.
