### ISSUE TITLE
.npm ignore images dir

### ISSUE THREAD

**Issue by ORESoftware** [hapijs/boom#144]
Hi all

Just wondering if you wouldn't mind adding the images dir to your` .npmignore` file?

When running du . on a node_modules installation I see:

```
24      ./boom/test
12      ./boom/lib
36      ./boom/images
```

In most cases you can .npmignore the test dir too, as most of the time that's not needed on NPM either, test dir is only needed on Github etc. thanks!

**Comment by Marsup** [comment]
It's been ignored for a very long time, upgrade your boom module.

**Comment by the1mills** [comment]
Well I looked in your .npmignore file...does the asterisk cover the images dir?

I am not importing your module directly, only indirectly so I don't hv control.

**Comment by Marsup** [comment]
Then ask for an upgrade where it's used.

**Comment by ORESoftware** [comment]
Turns out NPM ignores node_modules  anyway, you don't need to add it to
npmignore - what's in there after an install is to satisfy different
versions of same package.
