### ISSUE TITLE
Unauthorized 

### ISSUE THREAD

**Issue by simon-p-r** [hapijs/boom#146]
When using unauthorized with negotiate scheme I cannot send back the token in the header, I want to return the header like this

**WWW-Authenticate: Negotiate <base 64 encoded string>**

I use boom like this, token variable being the base64 encoded string

                            return reply(Boom.unauthorized(null, 'Negotiate', token));

However I then get this in http response

    'www-authenticate': 'Negotiate 0="o", 1="R", 2="U", 3="w", 4="E", 5="6", 6="A"
    , 7="D", 8="C", 9="g", 10="E", 11="D", 12="o", 13="Q", 14="w", 15="G", 16="C", 1
    7="i", 18="s", 19="G", 20="A", 21="Q", 22="Q", 23="B", 24="g", 25="j", 26="c", 2
    7="C", 28="A", 29="g", 30="o", 31="="',

I could work on a PR if you want to allow the ability to send just one string against the scheme.

**Comment by hueniverse** [comment]
This format is not supported. The third argument is expected to be an object. A PR would be fine, as long as it is super simple and clean.
