### ISSUE TITLE
Remove line from wrap function

### ISSUE THREAD

**Issue by niftylettuce** [hapijs/boom#148]
https://github.com/hapijs/boom/blob/master/lib/index.js#L76

This causes #139 to break...

**Comment by dunnock** [comment]
Same issue, the condition is wrong https://github.com/hapijs/boom/commit/3aa4a8c05e88646c22edac2e876411d8d3d61b06#commitcomment-21496008

**Comment by zaggino** [comment]
Related issue - https://github.com/hapijs/boom/issues/142

**Comment by AdriVanHoudt** [comment]
PR's are always welcome ;)

**Comment by dunnock** [comment]
I will take it
