### ISSUE TITLE
Question about Boom response to the client

### ISSUE THREAD

**Issue by roytz** [hapijs/boom#150]
Hi,
I really like using this package! Just one small question, I use Boom to return response to the client but Boom doesn't return all the fields (such as 'isBoom' or many other fields) and I wonder why? Of course there's data that I don't want the client to get for security reasons but if that's the case, why are those fields exist at all? I mean, who should use them (assuming it's not the client).
Thanks!

**Comment by arb** [comment]
https://github.com/hapijs/boom#faq

**Comment by shai32** [comment]
@arb its not answering the question, why do I need the isBoom and isServer?
I am creating the boom in the server, so I know its a boom and I know its status (isServer)
so its not needed.

**Comment by Marsup** [comment]
Boom errors are serialized before being sent to the client, to do that the server needs some information, that's classic OOP. It's done this way because subclassing errors in JS is a nightmare, you can ignore those fields unless want to post-process errors.

**Comment by shai32** [comment]
So the logic how to serialize the boom is part of this package?
if so, where can I see it in the source code?

**Comment by Marsup** [comment]
No it's in hapi. Out of curiosity why is that of any interest to you ?

**Comment by shai32** [comment]
If there is something that I don't see why its there, it can be for 2 reasons:
1. I Don't use the package as I should, so I need to understand what I am missing, and start using it right
2. less likely but it can be that the there is some improvement need to make to the package, so its good that it will be an issue open about it. 

I still don't understand why isBoom is there, who use it?
hapi does't know what to do with isBoom field.
so if hapi doesn't use it, so who does?

**Comment by roytz** [comment]
@Marsup, Is this data should be used by a "middleware" of some kind? Like a microservice calling this API function and getting the (full) Boom response, process it. do whatever and only then pass it back to the client?

**Comment by Marsup** [comment]
@shai32 hapi is using those fields, you didn't look hard enough.
@roytz usually to intercept routes replies and manipulate those errors to eg. add or remove information, or change the reply entirely.
