### ISSUE TITLE
Additional error to payload instead to message

### ISSUE THREAD

**Issue by FraVieMor** [hapijs/boom#153]
Boom errors allows pass custom data like this:

`Boom.badRequest([message], [data])
`
Returns a 400 Bad Request error where:

- `message` - optional message.
- `data` - optional additional error data.

`Boom.badRequest('invalid query', 'additional error data');`

Generates the following response payload:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "invalid query"
}
```
Without additional error data. This is because `data` is not added to payload like here:

```
let error = Boom.badRequest('invalid query');
error.output.payload.custom = 'additional error data';
```

What generates the following response payload:

```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "invalid query",
    "custom": "additional error data"
}
```
Is there any method to do that?

**Comment by liviur** [comment]
Hi,

I have a similar issue,
I'm trying to create my own error:
`reply(Boom.create(500, 'Internal Server Error', { validation: validationErrors }));`
(Also tried with the `badRequest` method)

and I'm getting the generic:
```
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred"
}
```
while expecting something like:
```
{
  "statusCode": 500,
  "message": "Validation failed",
  "data": [
    "Polling interval must be bigger than 5 seconds"
  ]
}
```

Which can be manually achieved through:
```
        reply({
          statusCode: 500,
          message: errorMessage,
          data: validationErrors,
        }).code(500);
```

Which is what I'm trying to avoid using Boom.

Would love to know what I'm missing.

**Comment by arb** [comment]
Are you using hapi or are you using another http server?

**Comment by liviur** [comment]
@arb - Using Hapi

**Comment by arb** [comment]
Have you read https://github.com/hapijs/boom#faq ?

**Comment by liviur** [comment]
Read it now. Thanks.
If so - what's the point of getting the data in the Boom object if I have to than manipulate it manually each time?

How is the data field used than? Whats a legitimate use case that i could see the data result without getting all "down and dirty"

**Comment by arb** [comment]
It's there so you can make your own errors + have more complete logs on the server. hapi strips it out to prevent leaking data back to the client but (I THINK) logs the whole error.

**Comment by jmonster** [comment]
@FraVieMor your proposed solution is the only solution right now -- `message` must be a string. I think it would make sense for Boom to also accept an object, though.

@arb you're correct but unfortunately if error `isBoom` then [💥](https://github.com/hapijs/boom/issues/152) 🙊 -- https://github.com/hapijs/boom/issues/152
