### ISSUE TITLE
Boom.wrap with a provided message doesn't format the payload

### ISSUE THREAD

**Issue by alonl** [hapijs/boom#154]
Boom.wrap with a provided message doesn't format the payload.

Reproduction steps:
```
> const Boom = require('boom');
> var err = new Error("some error message");
> var boomErr = Boom.wrap(err, 400, "modified error message");

> // actual result:
> boomErr.output.payload
{ statusCode: 400,
  error: 'Bad Request',
  message: 'some error message' }

> boomErr.reformat();
> // expected result:
> boomErr.output.payload
{ statusCode: 400,
  error: 'Bad Request',
  message: 'modified error message: some error message' }
```

The consequence is that I have to call `err.reformat()` after every call to `Boom.wrap` with a provided error message - is this the desired behavior? 

BTW, to my observation, the problem is [here](https://github.com/hapijs/boom/blob/v4.3.1/lib/index.js#L124), where `reformat()` is called before the message is set.

Many thanks!

**Comment by hueniverse** [comment]
I am marking this as a breaking change because it will now set a message in the payload when non provided. I would normally release this as a patch but since this is going to change actual API response payloads in some cases, I feel the safe thing to do is a major.
