### ISSUE TITLE
Duplicate error code in both the error object and the payload

### ISSUE THREAD

**Issue by EugeneAbramchuk** [hapijs/boom#155]
There are two error codes entries, one of which is redundant, please consider dropping. In my view, the one in payload is the obsolete one.

```
var Boom = require('boom');
global.console.log(Boom.badRequest('msg'))
{ Error: msg
    at repl:1:25
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:544:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
    at REPLServer.Interface._onLine (readline.js:247:10)
    at REPLServer.Interface._line (readline.js:591:8)
    at REPLServer.Interface._ttyWrite (readline.js:870:14)
    at REPLServer.self._ttyWrite (repl.js:617:7)
    at ReadStream.onkeypress (readline.js:126:10)
    at emitTwo (events.js:106:13)
  data: null,
  isBoom: true,
  isServer: false,
  output: 
   { statusCode: 400, <--- the first one
     payload: { statusCode: 400, error: 'Bad Request', message: 'msg' }, <--- the second one
     headers: {} },
  reformat: [Function] }
```

This leads to duplicate information being logged once the object is unwrapped:

> code=ACCESS_KEY_NOT_FOUND, isBoom=true, isServer=false, **statusCode=401, statusCode=401**, error=Unauthorized, message=Access key not found, code=ACCESS_KEY_NOT_FOUND

**Comment by AJamesPhillips** [comment]
Hey @EugeneAbramchuk, was wondering what the challenge is with the duplicate information, can you just ignore one value (you choose)?

Also have you dug into the Hapi source code as any change would need to be compatible with that large code base.

Finally for client side scripts it is convenient to have access to the payload status code in a simple accessible way through the payload, though I'm not sure if that's the original reason it's included.

**Comment by EugeneAbramchuk** [comment]
@AJamesPhillips I understand your concerns about compatibility, though I still cannot fathom why would we need two duplicate statusCode keys in the same object - albeit at different hierarchy levels. Am I the first to ever raise this question? (seems so, for I cannot find any mentions of it anywhere)

The errors are logged "as is" without parsing them, therefore it ends up in the logs.

**Comment by AJamesPhillips** [comment]
:)  Understood.  Perhaps useful, [have you checked out Good](https://github.com/hapijs/good)?  It gives you nicer error logs unless you're looking for the whole error message as is, but then you could use a custom handler function to format it (I haven't but I'm 99% certain it's easily doable).  If it's an uncaught exception you can also [use poop](https://github.com/hapijs/poop) (Thank hueniverse for the name!  :P)

**Comment by arb** [comment]
It's like that because that's how hapi uses it.

**Comment by hueniverse** [comment]
The error payload and the error data are not the same thing in some cases.
