### ISSUE TITLE
Can boom package be used only for server-side development?

### ISSUE THREAD

**Issue by vguzev** [hapijs/boom#158]
Hello,

First of all, guys, thanks a lot for your project! It really simplifies our backend tasks a lot! )

When we perform REST-request to the server it can:
1) return some data;
2) fail with server-side errors wrapped in Boom structure;
3) fail with some client-side errors (like timeout, network not found and etc). 

In case №3 it is convenient to wrap error with Boom error structure as well (to get the same structure for both serverside and clientside errors). That's why it would be great to use boom library on frontend as well...

I've seen your posts regarding your position that you're not going to transpile to ES3 (see https://github.com/hapijs/boom/issues/135). OK, we can transpile node_modules/boom with Babel in our projects. But the problem is that you're using features that are not supported at runtime by Major browsers (like IE11). For example, I see that ```Error.captureStackTrace``` is used in code - and it is supported only in V8... Internet Explorer crashes when we try to use Boom...

So, I want to say that it must be stated clearly which JavaScript engines/browsers Boom does support and which browsers are not supported. If you're supporting only Node V8 then it must be stated clearly in README.md at the top line: 
```diff
- DO NOT USE THIS LIBRARY IN FRONTEND DEVELOPMENT! ONLY NODE V8 IS SUPPORTED!
```
This will save a lot of time for both maintainers and users of this package.

Thanks!

**Comment by WesTyler** [comment]
>If you're supporting only Node V8 then it must be stated clearly in README.md at the top line

To be fair, this is an npm package which in and of itself suggests usage in Node.js ...

**Comment by vguzev** [comment]
@WesTyler When someone visit and read main page here https://github.com/hapijs/boom or here https://www.npmjs.com/package/boom he has no idea about such restriction... The only way is to try using it and fail... This is really annoying and frustrating experience.

**Comment by sinxwal** [comment]
@WesTyler npm != Node.js. 
We use npm packages to build frontend app on js, but don`t use Node on back at all.

**Comment by WesTyler** [comment]
Fair point. :P

**Comment by Marsup** [comment]
There can certainly be feature detection, but why would you want boom in the browser in the 1st place ?

**Comment by vguzev** [comment]
@Marsup Let's suppose that we have the Hapijs-based backend, written by someone else. The REST specs say that every error is wrapped in magical "Boom structure". Usually on frontend we use superagent (https://www.npmjs.com/package/superagent) to request data from server. But superagent returns errors in different format, not compatible with Boom error messages.

So, in our code we have to do something like this:
```typescript
try {
  const result = await makeRequest();
  // Do something with result
}
catch (e) {
 if (e.isBoom) {
  // This is server-side error - handle it
 } else {
  // This is client-side error - handle it as well
 }
}
```
In UI both error handling branches should display errors in the same way, but errors ```e``` are coming in different formats. We want to create a Boom wrapper for superagent's client errors in our service layer, so that our code could be simplified:
```typescript
try {
  const result = await makeRequest();
  // Do something with result
}
catch (e) {
  // This is server or client-side error - handle it
}
```
OK. How can we do that? We know that errors are in "Boom" format. Go Google it and get familiar with this "boom" package. It is logical that the best way to create boom wrappers is via Boom.wrap, or Boom.create from boom package... that's how boom library comes to the frontend.

P.S. And for me, as a frontend developer, it was quite strange to see that ```boom.isServer``` returns ```false``` for server-side errors with 4xx codes... I expected it to be false only when server is unavailable/there are some connection problems. Again, all this happened because we didn't know that this package is designed to be used only for backend development!

**Comment by WesTyler** [comment]
Should we do something like [Joi](https://github.com/hapijs/joi/#browsers)?

**Comment by Marsup** [comment]
Hapi speaks http unless you query from the server and use `server.inject`, which is certainly not what a client would do. So you don't have to know boom or wrap boom on the client-side to do anything, all of its properties are hidden, all that remains is a code and a message. I still don't see why you need boom on the client.

**Comment by vguzev** [comment]
@WesTyler Generally I see two options for further development:
1. Add some browser-detection features in current package. For example, instead of 
```Error.captureStackTrace(...)``` do ```if (Error.captureStackTrace) { Error.captureStackTrace(...) }```. In this case you should transpile it to ECMA Script 3, so that this library is compatible with as many browsers as possible.
2. Fork this library to ```boom-frontend``` (or whatever you name it), set it's target to ES3. And leave the current ```boom``` package as it is. In this case there will be two different packages - one for backend, and one for frontend.

**Comment by WesTyler** [comment]
I personally would rather not add browser detection into Boom itself, but I'm not the decision-maker here :P.

I should have been more specific in my last comment. Should we do something like Joi and add a disclaimer at the bottom that says "This isn't intended for browser usage and probably won't work. If you need to use it, check out [this browser-specific fork](link-to-future-plugin)"

**Comment by vguzev** [comment]
@Marsup We're programming in Typescript, not in pure "typeless" JavaScript... That means that the interfaces for both server-side errors and client-side errors must be the same. Looking back to the code above it should look like:
```
try {
  const result = await makeRequest();
  // Do something with result
}
catch (e: IError) {
  // This is server or client-side error - handle it
}
```
Of course we could create our own structure IError, and convert Boom errors to this format... but why should we do this when Boom's error structure is what we actually need?

**Comment by Marsup** [comment]
From the client-side perspective you're still not getting boom errors, though boom is used to help passing them around and ultimately hapi will serialize them into something else to pass over http. That still doesn't seem to involve having boom as a client-side library.

**Comment by vguzev** [comment]
@WesTyler Sure, that should be done now. And actually this is the second option from my previous comment https://github.com/hapijs/boom/issues/158#issuecomment-307148199.

**Comment by WesTyler** [comment]
Regardless of the merits (or lack thereof) of having Boom in the browser, I think the main "action item" for this issue is to decide if Boom needs the disclaimer. Then if *someone* ;) wants to build a browser-compatible fork, the rest of the discussion could be had there.

**Comment by Marsup** [comment]
I personally don't think it needs a disclaimer since this package doesn't make any sense in browser-land, but if it helps clarify any doubt...

**Comment by vguzev** [comment]
@Marsup I've described above https://github.com/hapijs/boom/issues/158#issuecomment-307143351 how I found this package. The current description of the package doesn't say that it "doesn't make any sense in browser-land".

**Comment by Marsup** [comment]
Let me know where you saw : `The REST specs say that every error is wrapped in magical "Boom structure".`, maybe this is what needs clarification. From where I stand, the hapi docs (https://hapijs.com/api#error-response) mention `When the error is sent back to the client, the response contains a JSON object with the statusCode, error, and message keys.`, which is quite clear.

**Comment by WesTyler** [comment]
> I personally don't think it needs a disclaimer since this package doesn't make any sense in browser-land

I actually agree here. But if people are missing something along the way, this doesn't cost us much and doesn't clutter the README too bad.

**Comment by hueniverse** [comment]
As a general rule, I don't want to add anything that is not required because it does add complexity. It is more stuff people using this module need to read. I would treat this issues the same way I treat all other requests I don't see value in - let it sit and see if this is an issue shared by others. I don't make adjustments for one person when I disagree as a matter of practicality.

Specifically, there is no reason to use this on the client. If you think you should, you have deeper understanding problems with the hapi.js stack that a simple readme cannot resolve.

**Comment by vguzev** [comment]
OK, it's your decision. I'm closing this issue for now. I've got your confirmation that you're not going to support other browsers. So, we're currently in process of removing boom package from dependencies of our frontend projects.

**Comment by Marsup** [comment]
It's not a question of supporting browsers, it doesn't make sense there!
