### ISSUE TITLE
Boom.wrap string fails

### ISSUE THREAD

**Issue by danielb2** [hapijs/boom#162]
Boom.wrap on an error converts it into a 500 error. Why not do the same thing for a string?

I tend to think of Boom.wrap to wrap things to make it easier, so why expect `Boom.wrap(new Error('blah'))` instead of just `Boom.wrap('blah')`.  Is there a good use-case for throwing errors on strings?

**Comment by hueniverse** [comment]
Strings are not errors. This is not a valid use case.

**Comment by danielb2** [comment]
considering that the normal callback paradigm tends to be `(err, something) =>`  and standard practice is to consider err an error as long as it's not null, I don't think it's crazy to assume that err can be a string sometimes.

**Comment by danielb2** [comment]
I end up doing:

```
try {
    return Boom.wrap(err);
}
catch (e) {
    return Boom.wrap(new Error(err));
}
```

or check typeof(err) and if it's an error, then I wrap it in boom, otherwise I create an error.

But I do it so much, it would be easier if wrap just wrapped things and created Booms.  The name is generic enough.

**Comment by hueniverse** [comment]
Nope. String is not an error. If anything passes string as an error, it's a bug. Fix that.
