### ISSUE TITLE
Boomify Api  default override options not working.

### ISSUE THREAD

**Issue by Samueljoli** [hapijs/boom#163]
Not sure if the documentation or the source needs to be updated depending on actual intention. But when `Boomify` is given a non boom, plain Error object with message and statusCode set, override does not inherit those settings.

Eg.
```js
const error = new Error('some-message');
error.statusCode = 400;

Boom.boomify(error)
//Produces this output
{ Error: some-message
    at repl:1:13
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:504:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
  statusCode: 400,
  isBoom: true,
  isServer: true,
  data: null,
  output:
   { statusCode: 500,
     payload:
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function] }
```

If you notice the statusCode is set to `500` although my original error object had a statusCode set to 400.

`Defaults to true (apply the provided statusCode and message options to the error regardless of its type, Error or boom object).` This line in the documentation is false.

**Comment by hueniverse** [comment]
You can't create your own boom-like error and expect that to work. `override` is meant to be used only with a Boom object.

**Comment by Samueljoli** [comment]
Hey @hueniverse,

 🤔 , then is this line in the documentation misleading? => `Defaults to true (apply the provided statusCode and message options to the error regardless of its type, Error or boom object)`

**Comment by hueniverse** [comment]
No. `boomify()` is not expecting you to set boom properties on your error and then expect it to retain those. The status code is taken from either a `Boom` object or the arguments passed to the function. You are providing neither and ending up with the default value of `500`.

We can clarify that you cannot set your own `statusCode` on a non-`Boom` object and expect that to work. That's about it.

**Comment by Samueljoli** [comment]
Hey @hueniverse,

That makes sense, but yeah maybe that little snippet would be helpful. It wasn't just me that found that to be a bit confusing.

**Comment by hueniverse** [comment]
I don't know how to clarify this. You are passing an object with a random `statusCode` property. That's not even a thing on **boom** objects...
