### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by mirzazeyrek** [hapijs/boom#164]
This error message started to appear recently. Is there anything you guys suggest may be ?

/node_modules/grunt-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
11:16:32 const Hoek = require('hoek');
11:16:32 ^^^^^
11:16:32 SyntaxError: Use of const in strict mode.
11:16:32 at exports.runInThisContext (vm.js:73:16)
11:16:32 at Module._compile (module.js:443:25)
11:16:32 at Object.Module._extensions..js (module.js:478:10)
11:16:32 at Module.load (module.js:355:32)
11:16:32 at Function.Module._load (module.js:310:12)
11:16:32 at Module.require (module.js:365:17)
11:16:32 at require (module.js:384:17)
11:16:32 at Object. (/var/jenkins/workspace/artbees-portal/pr/253/node_modules/grunt-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)
11:16:32 at Module._compile (module.js:460:26)
11:16:32 at Object.Module._extensions..js (module.js:478:10)

**Comment by Marsup** [comment]
You're using a version of nodejs that's too old.

**Comment by AdriVanHoudt** [comment]
I saw this passing by on twitter. Also broke request :P Hawk updated to a version of hoek that started using const with a minor or patch bump...

**Comment by Marsup** [comment]
It's pre 4, nobody should be using those versions today, it's insecure.

**Comment by esphen** [comment]
Well, it's used by hawk, which is used by request, which is used by node-sass, which is used by grunt-sass. So now the sass-files of our legacy webapps aren't building on the CI without us doing any changes to our dependencies :)

**Comment by mirzazeyrek** [comment]
@esphen this is exactly what we are going through luckily I was able to find a solution after some digging through the web!

https://github.com/sass/node-sass/issues/2100#issuecomment-330881630

@Marsup Yeah but it's not always possible to convince your p.m. to give some time to just update npm and solve all the errors from legacy packages during the process !

**Comment by pagameba** [comment]
This has broken all our ci and deployments, agreed nobody *should* be using those versions but some of us are stuck with legacy systems.  Semver.

**Comment by AdriVanHoudt** [comment]
See https://github.com/request/request/issues/2772#issuecomment-330879495 for more info.

**Comment by Marsup** [comment]
It doesn't seem to be our fault here, but as you already found out, shrinkwrap is your friend for legacy apps. Or any app you release really. FWIW request has been declaring support for node engine >= 4 since 11 months according to the commit log, you have probably seen those warnings months ago in your npm logs and willfully decided to ignore it, it's a bit unfair to wake up now.

I hope you carefully assessed the risks of running a vulnerable node version and that your PM is OK with making your company take those risks.

**Comment by AdriVanHoudt** [comment]
Even more context if you want https://medium.com/@eranhammer/on-being-operationally-incompetent-4ca4fbccbf98

**Comment by hueniverse** [comment]
https://github.com/request/request/issues/2831
