### ISSUE TITLE
lower the Node requirement to Node 6

### ISSUE THREAD

**Issue by mcollina** [hapijs/boom#166]
Boom is used in other modules that are not part of Hapi, and it might be handy to keep it compatible to Node 6 for the time being. Boom works on Node 6, or at least my tests are not failing on Node 6 because of unsupported syntax.

**Comment by Marsup** [comment]
Boom is pretty stable, if you need guarantees why not stick to 5.x ?

**Comment by mcollina** [comment]
Because it’s really stable, why removing Node 6? And to some extent Node 4?

Blocking a version means that at some point, it would become obsolete, and the cost of migrating will be higher. I get that some libraries might require Node 8 for async/await or other key features, but Boom seems done.

**Comment by kanongil** [comment]
Setting less than 8, would mean that boom can't use the latest `hoek`, which keeps it from receiving the latest updates, and requires an install of hapi to install two versions of `hoek`.

**Comment by StarpTech** [comment]
I don't understand why the hapi ecosystem is moved to 8 when the current LTS Version is 6 https://github.com/nodejs/Release#release-schedule @kanongil hoek is compatible with Node 6 only the tests are using Async / Await. Some syntactic sugar is preferred over accessibility. That's sad.

**Comment by AdriVanHoudt** [comment]
@StarpTech The LTS of 8 is in 1 month(? not sure when exactly, graphics say october but json states 31st of oct) so hapi is moving to that in preparation, since moving takes a while

**Comment by mcollina** [comment]
It’s on the 31st of October.

**Comment by StarpTech** [comment]
@AdriVanHoudt Node 6 is still maintained until 2019 and what's the need do you see to change to 8 ? Only to use async / await in tests?

**Comment by AdriVanHoudt** [comment]
@StarpTech I would async/await everywhere not only in tests. If it is about Boom it is more about the whole hapi ecosystem moving to node 8 at once. See @kanongil's comment for example.

**Comment by Marsup** [comment]
v17 is setting a baseline on node 8, who said we abandoned v16 though ?

**Comment by hueniverse** [comment]
hapi v16 will be supported until node v4 is out of LTS. That means security and critical bug fixes. You can safely stay on hapi v16 for a while. It does mean no more improvements across the core ecosystem, but will include bug fixes and security fixes. Individual maintainers of the core modules (such as boom and hoek) will have the freedom to push out new versions of the node v4 supported modules if they want to backport enhancements or non-critical bug fixes.

I am not going to figure out which feature used requires which version of node per module and try to be as flexible as possible. This is a losing proposition. The hapi ecosystem is moving to node v8 with the next major release. You will have plenty of time to transition while being supported under v16.

**Comment by sholladay** [comment]
I just want to say that, personally, I'm excited to see the hapi ecosystem continue to stay on top of new Node releases soon after they come out and use them as a baseline. I'm so sick of other tech stacks that age and rot badly because they are slow to update their dependencies. It often results in long-lasting security vulnerabilities. Thanks for all of your hard work maintaining it all. ❤️
