### ISSUE TITLE
set isDeveloperError when statusCode is 500

### ISSUE THREAD

**Issue by csrl** [hapijs/boom#168]
I want to mask 502, 503 and 504 errors as 500 errors to return to the client.  I do not want to expose internal details that a particular endpoint is a proxy or makes additional internal service requests that result in an eg. 502 bad gateway error.  For my purposes, this is acceptable.

In my attempt to make that so, if an error occurs on an internal request, I wrap it with Boom.boomify(err, {statusCode: 500}), and I expected that I'd see the stack trace output on the server logs, and the client would just get the standard 500 response.  While the client did get the proper response, the server output didn't provide the error stack trace log output.

Looking closer, I find that isDeveloperError must be set to true for that to occur.  The only place that is set is in Boom.badImplementation().  Would it be reasonable to instead set that flag in the reformat function where the payload message is generically rewritten?

```javascript
internals.reformat = function () {

    this.output.payload.statusCode = this.output.statusCode;
    this.output.payload.error = internals.STATUS_CODES[this.output.statusCode] || 'Unknown';

    if (this.output.statusCode === 500) {
        this.output.payload.message = 'An internal server error occurred';              // Hide actual error from user
        this.isDeveloperError = true;
    }
    else if (this.message) {
        this.output.payload.message = this.message;
    }
};
```

**Comment by csrl** [comment]
Alternatively, it'd be great if Boom.badImplementation would just accept any input error, regardless if it is already a Boom error, and convert it to a 500 error.  It seems like a pretty acceptable concept, that some internal request has failed, and that should be returned as a 500 error to the client, regardless of what type of error it was.

**Comment by hueniverse** [comment]
Just pass the boom error as the second argument to `badImplementation()`.

**Comment by csrl** [comment]
Well that was simple.  Thanks.

Still, I don't see why 500 responses are treated differently.  I'm not sure under what circumstances a 500 error could be produced that isn't an implementation error deserving of the 'implementation' tag.

**Comment by hueniverse** [comment]
Errors such as `SyntaxError` are developer errors. The one you listed are not.
