### ISSUE TITLE
Docs should display Node versions supported

### ISSUE THREAD

**Issue by stringbeans** [hapijs/boom#169]
Maybe a minor issue, but I noticed your documentation doesnt specify which node versions are supported. I'm currently using Node 5.11 and this package does not work because the dependency `hoek` has a function defined like so: `exports.assert = function (condition, ...args) {}` and the `...args` spread syntax is not supported

**Comment by WesTyler** [comment]
Good call. We have a similar PSA on many other hapi repos. I'll do this right now.

**Comment by Marsup** [comment]
I've never seen any module do that. Developers know how to read a package.json usually.

**Comment by WesTyler** [comment]
I would have bet money that at minimum Glue and Hoek had that.. but now I can't find it... I may very well be crazy.

**Comment by stringbeans** [comment]
thanks guys :)

**Comment by hueniverse** [comment]
I don't want to start doing that on dozens of modules when the package.json is the sole authority. We work hard to keep the engine setting up to date.

**Comment by stringbeans** [comment]
@hueniverse @Marsup  i think thats fair, i should've checked the package.json to verify which version of Node is supported. However, something tells me that the current setting `>=8.9.0` is inaccurate... i wouldnt think that `boom` is ONLY supported by the latest version of Node...

**Comment by Marsup** [comment]
That's not what it supports but what we target. If you assume differently you take the risk of being hit by a breaking change for you that we don't consider breaking because it's within the range we declare.
