### ISSUE TITLE
Can't find boom-7.1.0.tgz

### ISSUE THREAD

**Issue by roytz** [hapijs/boom#174]
I know it's probably not the place but any idea why I suddenly get this error

> https://registry.yarnpkg.com/boom/-/boom-7.1.0.tgz: Request failed \"404 Not Found\"

whenever I run `yarn`?
I've been using hapi an boom for a long time now and this is the first time I get this error

**Comment by twhitbeck** [comment]
why did you close this?

**Comment by hueniverse** [comment]
You don't need 7.1.0. Just install latest.
