### ISSUE TITLE
add Boom.serverError() helper method for 500 response status

### ISSUE THREAD

**Issue by csrl** [hapijs/boom#175]
In issue #168 it was clarified that `Boom.badImplementation()` use case was for "developer errors" (eg. coding mistakes such as a `SyntaxError`), and not suitable for other types of server errors, such as a resource not being available.

So, this is a request to add a generic `Boom.serverError()` helper method.  Ideally, it would be done in a compatible way with hapi logging such that the full error message shows up in the logs.

**Comment by hueniverse** [comment]
That's just `Boom.internal()`

**Comment by csrl** [comment]
The documentation just shows Boom.internal() as an alias of Boom.badImplementation().  But now I see that it is not.  Thanks.
