### ISSUE TITLE
what happened to v7.1.0

### ISSUE THREAD

**Issue by twhitbeck** [hapijs/boom#176]
trying to figure out what's going on here.

Why is v4.1.0 listed as the "latest" release in GitHub? npm says (right now) that v7.1.1 is the latest.

At one time, there was a v7.1.0 on npm. Where did it go? Did you unpublish it? Users of yarn are going to be bitten by this, since 7.1.0 tgz is referenced in the `yarn.lock` file.

**Comment by hueniverse** [comment]
What yard.lock file are you talking about?

**Comment by twhitbeck** [comment]
I meant a user of yarn, if they had installed when 7.1.0 was available, then 7.1.0 is listed in their project's `yarn.lock` file. npm version >5 has similar behavior with `package-lock.json`. I don't know for sure how npm will respond if the `package-lock.json` file lists boom 7.1.0. Yarn just blew up with error about unable to find 7.1.0 tgz in the yarn registry.

I guess unpublishing is your call, just be aware of how that affects your users.

**Comment by hueniverse** [comment]
Sounds like breaking for those users is the right outcome because they need to be forced to update their dependencies.
