### ISSUE TITLE
Override Boom messages

### ISSUE THREAD

**Issue by damusix** [hapijs/boom#192]
Can there possibly be way to override `internals.codes` messages so they are translatable?

**Comment by damusix** [comment]
This is true. I can always rewrap responses, but was wonder if it would be reasonable to request this. I am attempting to keep things as minimal as possible, eg: 

``` javascript
/* route handler => */
return (await User.find({ where: { id: 5 } })) || Boom.notFound()
/* ... */
```

But I am also wanting to give my app translations including errors since they will be used on the frontend.

**Comment by hueniverse** [comment]
If @arb wants to export the internal object, I am not going to object.

**Comment by arb** [comment]
@damusix in my experience it's atypical to do translations on the back end like that. The front end should have some kind of dictionary to map status code 404 to whatever language you'd like the user to see. Why do you want to do this on the back end?

**Comment by damusix** [comment]
@arb Really it was to avoid a dictionary map; but you're right, I should just make one given that I will probably end up making one anyways. Thanks for the quick response.
