### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by Seluj78** [hapijs/boom#194]
Do you think a python port would be doable ?

**Comment by arb** [comment]
I'm not sure I understand the question. Sure, if someone in the python community wanted to port this that would be fine.

As far as the license goes, I am not an expert, so I'd have to der to @hueniverse if there are any legal concerns (I sort of doubt that there is though)

**Comment by Seluj78** [comment]
Well, I'm currently building a python API and stumbled upon `boom`. I like the project and all, but I'm working with python, not js :smile:

**Comment by hueniverse** [comment]
Nothing is stopping you...
