### ISSUE TITLE
Include message when converted to json

### ISSUE THREAD

**Issue by erfanio** [hapijs/boom#198]
I think most people log their errors in a json formatted file or something similar. But in doing that the message that the error was created with isn't being preserved in `>= 500` errors.

Current behaviour
```javascript
JSON.stringify(Boom.internal('maybe valuable info'), null, 2)
```
```json
{
  "data": null,
  "isBoom": true,
  "isServer": true,
  "output": {
    "statusCode": 500,
    "payload": {
      "statusCode": 500,
      "error": "Internal Server Error",
      "message": "An internal server error occurred"
    },
    "headers": {}
  }
}
```

**Comment by erfanio** [comment]
One option to fix this is to have a `toJSON` function on the error that will add the message to the object just before stringifying.

Something like adding this to `lib/index.js:395`

```js
err.toJSON = function () {
    const data = Object.assign({}, this);
    data.message = this.message;
    return data;
}
```

**Comment by hueniverse** [comment]
Boom is an Error object. We are not going to change how JS does this.
