### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by mattcoll** [hapijs/boom#199]
Hi, I am building a new Angular 6 web app and I am getting a moderate error regarding one of the dependencies of boom. If there is no breaking change are you able to update the hoek version >= 5.0.3

This is the error:
https://nodesecurity.io/advisories/566 
Versions of hoek prior to 4.2.1 and 5.0.3 are vulnerable to prototype pollution.

Thanks

**Comment by Marsup** [comment]
boom already takes the latest of hoek by virtue of semver, if you get something else, that's not because of boom.

**Comment by mattcoll** [comment]
Ok, Thanks!
What would you suggest? 
If Angualr 6 is using karma > log4js > loggly > request > hawk > boom > hoek
Do i just go back up the tree and make sure all modules are using the lastest?

![screen shot 2018-05-18 at 7 40 25 pm](https://user-images.githubusercontent.com/19816080/40229457-6e712a6a-5ad3-11e8-9965-5ee18566850f.png)

**Comment by Marsup** [comment]
`npm ls hoek` and see if you actually have a vulnerable version, it might just be the tool that you're using to scan that is confused.

**Comment by Marsup** [comment]
Both formats will get fixed versions. What worries me are projects stuck with old versions of request like in karma and node-sass, there's nothing we can do to make them move, so you'll have to ask them.

**Comment by mattcoll** [comment]
Yeah, makes things very difficult. I will try get something from them. 
Thanks again for your help!
