### ISSUE TITLE
Vulnerable version of hoek in Boom.

### ISSUE THREAD

**Issue by tcoz** [hapijs/boom#202]
Ran an inspection on my repo today, hoek came up as a known vulnerability. 

Here's the fragment from the package.lock:

"boom": {
      "version": "2.10.1",
      "resolved": "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz",
      "integrity": "sha1-OciRjO/1eZ+D+UkqhI9iWt0Mdm8=",
      "dev": true,
      "requires": {
        "hoek": "2.x.x"
      }
    },

Any chance you can upgrade hoek (it's at version 4+ now I think).

**Comment by Marsup** [comment]
Upgrade your version of boom and you'll get it.
