### ISSUE TITLE
More safe way to detect boom error

### ISSUE THREAD

**Issue by ikokostya** [hapijs/boom#209]
**Versions**

* node `v8.11.4`
* boom `7.2.0`

**Problem**

There are two ways for detecting boom errors: 

* `Boom.isBoom()` function
* `err.isBoom` property

Both are not "safe". For example, `Boom.isBoom()` function returns false positive result for non-boom error:

```js
'use strict';

const assert = require('assert');
const Boom = require('boom');

class NotBoom extends Error {}
const err = new NotBoom();
err.isBoom = true;

assert(Boom.isBoom(err));
```

**Suggestion**

Use [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) instead of property for detecting that error is a `Boom` error. For backward compatibility `isBoom` property can check this symbol.

Since the symbol will not be exported, external code can't mimic to `Boom` error.

**Comment by hueniverse** [comment]
We could though I don't see this as a real problem. It's still JS and if you want to create fake boom errors, why should I try and stop you...

**Comment by kanongil** [comment]
Boom can't safely use an internal symbol to do this, as multiple instances of the lib needs to work together. Thus, it won't detect boom objects created by an other instance.

A compromise could be to use `Symbol.for('isBoom')`, which would reduce the chance that it is set by coincidence. However, this makes it incompatible with all old boom instances, which makes it a very questionable change.

Note that you can also detect boom instances with `err instanceof Boom` (but this also relies on the `isBoom` property).

**Comment by ikokostya** [comment]
> Boom can't safely use an internal symbol to do this, as multiple instances of the lib needs to work together. Thus, it won't detect boom objects created by an other instance.

Could you explain what your mean? I suggest to use one symbol for all instances and don't export them:

```js
'use strict';    
    
const assert = require('assert');    
    
const isBoomSymbol = Symbol('boom');    
    
class Boom {    
    constructor() {    
        this[isBoomSymbol] = true;    
    }    
}    
    
function isBoom(err) {    
    return err[isBoomSymbol] === true;    
}    
    
const boomErr = new Boom();    
assert(isBoom(boomErr));    
    
class NotBoom extends Error {}    
const err = new NotBoom();    
err.isBoom = true;    
                                                                                          
assert(!isBoom(err));
```

> Note that you can also detect boom instances with `err instanceof Boom` (but this also relies on the `isBoom` property).

Current issue about unsafe behavior of `isBoom` property and `Boom.isBoom()` function which are [recommended](https://github.com/hapijs/boom#isboomerr) way to check `Boom` error instances.

**Comment by ikokostya** [comment]
Also, documentation for [`Boom.isBoom()`](https://github.com/hapijs/boom#isboomerr) function is incorrect:

> Same as calling instanceof Boom

But actually not: https://github.com/hapijs/boom/blob/75de5790200f467940b1919367fec75f80669d97/lib/index.js#L102

**Comment by ikokostya** [comment]
> Also, documentation for [`Boom.isBoom()`](https://github.com/hapijs/boom#isboomerr) function is incorrect:

Hmm. I am wrong:


```js
'use strict';    
    
const assert = require('assert');    
const Boom = require('boom');    
    
class NotBoom extends Error {}    
const notBoomErr = new NotBoom();    
notBoomErr.isBoom = true;    
    
assert(Boom.isBoom(notBoomErr));                                                          
assert(notBoomErr instanceof Boom);
```

This happens, because of [`Symbol.hasInstance`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/hasInstance) declaration for `Boom` class: https://github.com/hapijs/boom/blob/75de5790200f467940b1919367fec75f80669d97/lib/index.js#L75

So, I think this behavior is unobvious, because creating sub classes for errors is a most popular way to differentiate them.

**Comment by hueniverse** [comment]
Is this an actual problem or are you just being academic about it? I highly doubt you happened to have a namespace conflict with `isBoom`.

**Comment by ikokostya** [comment]
@hueniverse 

> Is this an actual problem 

This is *possible* problem. I think this is obviously from description of the issue.

> or are you just being academic about it? 

I just asked why actually need this fancy stuff at all? 

But instead of answering on question you decided to close the issue.

**Comment by hueniverse** [comment]
@kanongil explained the limitations we are dealing with. We need to know if an error is a boom object. We cannot use private symbols or instanceof checks because people use multiple copies of this module in their apps and hapi needs to grab all of them. We are not going to do a breaking change that requires the entire ecosystem to move to the new version just to avoid a theoretical problem.

Not sure what else can be done about this.
