### ISSUE TITLE
boom overrides existing properties on errors

### ISSUE THREAD

**Issue by SimonSchick** [hapijs/boom#212]
Title says all, I know this has been the case forever but imo boom should not alter thrown exceptions but instead wrap them and keep a reference to the `original` or `innerError` if you will.

If boom wishes to store extra information on errors I think it use non-enumerable symbols and not mess with user land objects.

**Comment by hueniverse** [comment]
This is not going to change.

**Comment by kanongil** [comment]
This is problematic, as it can cause compatibility problems. It is perfectly valid for some code to create an error, where eg. the `message` property is retrieved using a `getter` function. If this happens, as in #109, it can cause boom to throw an error when it tries to assign to that property.

A safer way to set it, would be using `Object.defineProperty()`. However, this can still throw if the property has been declared not `configurable`.

The "real" solution, that preserves the existing functionality, would probably involve using a `Proxy`.

For reference, one use-case for this, is lazy computation of the `message` property.

**Comment by hueniverse** [comment]
@kanongil I don't think this is the right issue to attach the actual concern onto... we can special case the only getter case.
