### ISSUE TITLE
Change default object structure

### ISSUE THREAD

**Issue by gkatsanos** [hapijs/boom#213]
Besides direct manipulation post-boom-object creation, I was wondering if there's an option or config which can instruct Boom to not generate an 
```
output: {
    payload: {
          ... 
    }
}
```
object but rather have it all flattened/unnested ..

The problem is I want to `delete` the stack (from production environments) and as I have both native Error objects and Boomified ones I find myself having to do 2 delete operators but also I need to check for the existence or not of error.output.payload before trying to delete error.output.payload.stack ..

**Comment by gkatsanos** [comment]
To demonstrate, I have to do this:
```
  converter: (err, req, res, next) => {
    if (env !== 'development') {
      delete err.stack;
    }
    if (env !== 'development' && err.isBoom) {
      delete err.output.payload.stack;
    }
..
```

**Comment by hueniverse** [comment]
Because that's what hapi uses to transmit the error back as an HTTP response.

**Comment by gkatsanos** [comment]
Anything we can do to configure that?

**Comment by hueniverse** [comment]
Configure what? What are you trying to solve? How do you end up with the stack in payload?

**Comment by gkatsanos** [comment]
> Configure what? What are you trying to solve? How do you end up with the stack in payload?

When I do a `const boomedError = new Boom('Validation failed', { statusCode: 422, data: err });` for example, the resulting object looks like:

```
boomedError ={
   data:[

   ],
   isBoom = true,
   isServer = false,
   message="Validation failed",
   output=   {
      headers=      {
         ...
      },
      payload=      {
         error = "Unprocessable Entity",
         message="Validation failed",
         statusCode = 422
      }
   }
```

So my question was if I can configure Boom so that I can have my own structure in the resulting object.

e.g. "status" instead of "statusCode", or, instead of having boomedError.output.payload.error / boomedError.output.payload.statusCode, to have directly boomedError.error, boomedError.status and so on.

I hope my question is clearer now?

**Comment by hueniverse** [comment]
You can do whatever you want but if you expect hapi to know what to do with it, then no. If you are not using boom with hapi, just create your own error module.

**Comment by gkatsanos** [comment]
I use express.
What do you mean create your own error module? Can you provide an example for reformat() ?
Many thanks!

**Comment by hueniverse** [comment]
I mean don't use boom. It is designed specifically for hapi. If you use express, a lot of its internals are meaningless to you. This module will always be about using it with hapi. It works with express, as is but if you need something a bit different, you need to fork and write your own solution. I think there is one such fork already but I don't know the name.

**Comment by gkatsanos** [comment]
Oh, okay! I was looking for similar solutions and Boom seemed by far the most popular. But indeed, it makes sense.
