### ISSUE TITLE
Add #unprocessableEntity for #badData

### ISSUE THREAD

**Issue by Dervol03** [hapijs/boom#214]
Hey guys.
First of all: thanks for this nice package.

However, when using it, I stumbled upon a confusing part of it: when I tried to trigger an `422 Unprocessable entity`, the method did not exist as `Boom.unprocessableEntity`. I had too look through the documentation to find that for this ONE HTTP Status, the method has a totally different name, based in its semantics `Boom.badData`. I don't mind having this method as an alias, but for consistency purposes, it would be nice if `Boom.unprocessableEntity` was there as well. :slightly_smiling_face: 

Cheers, guys,
Dervol

**Comment by roux1max** [comment]
Hey !

I think you could make a PR for this ;)
The code of this lib is pretty simple so if the maintainer wants to include it he will, if not he won't :)

**Comment by Dervol03** [comment]
Hi,

you are right and I actually would have opened a PR on this request, IF it didn't also involve changing the the interface definition in the `DefinitelyTyped` project. I've had to work twice with these people and it was a very unpleasant experience both times. Therefore, I don't touch any project that doesn't include its TypeScript typings itself, anymore. :slightly_frowning_face:

**Comment by hueniverse** [comment]
Happy to take a PR.

**Comment by Dervol03** [comment]
From a TypeScript user's perspective, I can't see both project in a separate way, as a change in one, without the same change in the other, won't bring me forward.
So, I'm sorry for being irrational. And if you decide to support TypeScript one day, either by moving the code to TypeScript or by adding own typings, I'll be happy support you. But as long as every change here relies on own submissions to DefinitelyTyped, the only thing left to me is to wish you the best for the future of the project :slightly_smiling_face:
