### ISSUE TITLE
Logging Boom error with Winston includes reformat() function

### ISSUE THREAD

**Issue by soulchild** [hapijs/boom#215]
I'm unsure whether this is the right place for this issue (or if it's rather a [Winston](https://github.com/winstonjs/winston) thing), but when logging Boom objects with Winston (e.g. Internal Server Errors), every error contains Boom's `reformat` function, making the log output somewhat confusing. 

Here's an example:

```js
error:  message=kaputt, stack=Error: kaputt
at Object.<anonymous> (auth.ts:27:16)
    at Generator.next (<anonymous>)
    at auth.ts:7:71
    at new Promise (<anonymous>)
    ...
at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5), data=null, isBoom=true, isServer=true, statusCode=500, statusCode=500, error=Internal Server Error, message=An internal server error occurred, , reformat=function (debug = false) {

    this.output.payload.statusCode = this.output.statusCode;
    this.output.payload.error = internals.codes.get(this.output.statusCode) || 'Unknown';

    if (this.output.statusCode === 500 && debug !== true) {
        this.output.payload.message = 'An internal server error occurred';              // Hide actual error from user
    }
    else if (this.message) {
        this.output.payload.message = this.message;
    }
}, typeof=internal(message, data, statusCode = 500) {

        return internals.serverError(message, data, statusCode, internals.Boom.internal);
    }
```

The code producing this is basically just the following Express error handler middleware:

```js
export default () => (err, req, res, next) => {
  Boom.boomify(err);
  if (err.isServer) {
    logger.error(err);
  }
  ...
}
```

Any ideas? I'm using winston@2 and the boom@7.3.0

**Comment by hueniverse** [comment]
I am not sure what Winston is doing, but `typeof` and `reformat` should not be enumerable keys which might be the reason they are currently included.

**Comment by hueniverse** [comment]
Adding `breaking change` as this can have side effects if the properties are being manipulated elsewhere unexpectedly. They shouldn't, so this is still a patch bug fix, but the label should help people debug if this breaks something.
