### ISSUE TITLE
Boom's interface cannot be using on Typescript.

### ISSUE THREAD

**Issue by gkawin** [hapijs/boom#223]
I try to assign a `Boom` interface into the first `error` argument on the express middleware in order to capture an error that was thrown from the handler function. But I can't import to that code. So I discovered how to use it by adding the 
```ts
export as namespace Boom
```
on the top of the type definition file. That's all solved completely.
My question is how can I open the PR to fix that? anyone could help me, please. Thank you

**Comment by hueniverse** [comment]
Sorry but this is the wrong place to ask this question. I don't knot where it the right place since I didn't write the TS definition for this module.
