### ISSUE TITLE
Format message interceptor

### ISSUE THREAD

**Issue by gabrielmsdiniz** [hapijs/boom#224]
I'd like to catch all Boom messages right before they are returned from API

e.g.: Imagine that I'm supposed to get better UX messages from API and I need to translate and format all the text messages that my API returns and I don't want to spend time changing one by one thrown error from my application.

Is there any Boom resource that can help me in this case? I didn't find out it

Maybe It would be great that exists a way to decorator boom...

is an interceptor from hapi response error the one solution?

**Comment by hueniverse** [comment]
You should use the hapi `onPreResponse` extension point to make any changes you want to the final error.
