### ISSUE TITLE
Error during unit test run since last update

### ISSUE THREAD

**Issue by KnutFr** [hapijs/boom#232]
Hi, 

Since last update (7.4.3) I encountered an error while executing unit test with mocha : 

```> tsp-back-node@1.0.0 test /Users/nd5783/Documents/Perso/tsp/manager/tsp-back-node
> nyc mocha -c -r ts-node/register src/**/*.spec.ts --exit

Error: Cannot find module 'boom'
```

The incriminated line is the load of Boom lib : 
`import Boom = require("boom")`

Do I have something to change with this last update ? Cannot see anything in changelog.

Out of unit test, my app run without problems and Boom error are throw successfully. 

 Npm : 6.10.3 Mocha : 6.2.0 Boom 7.4.3

Regards,

**Comment by hueniverse** [comment]
If you switched to use `@hapi/boom` in your package.json, you need to change your code to load the module with the scope. Otherwise, it's a problem in your code or config.
