### ISSUE TITLE
Boom 500 errors and logging

### ISSUE THREAD

**Issue by VirgileD** [hapijs/boom#258]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v12.13.0
* *module version*: 0.8.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi 18.4.0
* *any other relevant information*:

#### How can we help?

In the documentation the following sentence:
**All 500 errors hide your message from the end user. Your message is recorded in the server log.** let me believe that the error is recorded with server.log. But this is not the case. Is there a way to log the error without logging at each route?
I'm willing to PR either to correct the documentation or the code, jst let me know if you think it would be acceptable to server.log when hiding the 500 error.

**Comment by kanongil** [comment]
This is clearly a documentation issue, since boom itself does not include any server or logging mechanism.

**Comment by VirgileD** [comment]
okay, PR done, #259
