### ISSUE TITLE
Add change log or release notes.

### ISSUE THREAD

**Issue by darkobits** [hapijs/boom#264]
#### Context

* *node version*: 12.14.0
* *module version*: 7.4.11

#### What are you trying to achieve or the steps to reproduce ?

This project does not seem to have a change log, release notes, or other such resource, making it impossible to discern what breaking changes have been introduced across major version bumps without reading and fully comprehending the source diffs.

I would strongly encourage maintainers to consider adding release notes or using a tool like [`standard-version`](https://github.com/conventional-changelog/standard-version) or [`semantic-release`](https://github.com/semantic-release/semantic-release) which handle change log generation automatically provided the [conventional commits](https://www.conventionalcommits.org) standard is adhered-to.

**Comment by hueniverse** [comment]
![image](https://user-images.githubusercontent.com/56631/72123057-e5716d80-3314-11ea-9d80-b0721cee5050.png)
