### ISSUE TITLE
Restore support for nodejs v10?

### ISSUE THREAD

**Issue by thetumper** [hapijs/boom#268]
#### Support plan
* *which support plan is this issue covered by?* Community
* *is this issue currently blocking your project?* (yes/no):  no
* *is this issue affecting a production system?* (yes/no):  no

#### Context

* *node version*:  nodejs 10.15.3
* *module version*: @hapi/boom 9+
* *environment* (e.g. node, browser, native):  node
* *used with* (e.g. hapi application, another framework, standalone, ...): aws lambda
* *any other relevant information*:

#### What problem are you trying to solve?

NodeJS v10 is still in LTS for almost another year (until 4/30/2021), yet support is already removed in @hapi/boom.  The issue would be not being able to update @hapi/boom to take in fixes or feature updates, due to not being able to upgrade to node 12 at this time (due to limitations in enterprise infrastructure).

#### Do you have a new or modified API suggestion to solve the problem?

Suggest/request that @hapi would support "Maintenance LTS" versions of node, not only "Current" or "Active" development versions.

**Comment by hueniverse** [comment]
You can find which version is supported on which platform here: https://hapi.dev/module/boom/.

If you need additional support, paid plans are available.
