### ISSUE TITLE
Boom.wrap is not a function

### ISSUE THREAD

**Issue by RachitBhargava99** [hapijs/boom#269]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 14.3.0
* *module version*: 7.3.0
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): Express Application
* *any other relevant information*: I get this error whenever I attempt to wrap my error using Boom.wrap function (Boom.wrap(err, 500) for instance gives an error).

#### How can we help?

Here is a short snippet of where I am using this. Using this function raises the error, "TypeError: Boom.wrap is not a function"

```js
const Boom = require('boom')

exports.wrapNano = function wrapNanoError(cb) {
    return function(err) {
        if (err) {
            Boom.wrap(err, err.statusCode || 500)
        }
        cb.apply(null, arguments)
    }
}

**Comment by Marsup** [comment]
Using default's branch documentation on a very old version of the package is unlikely to work. Either use the up-to-date package (`@hapi/boom`) or refer to the old documentation.
