### ISSUE TITLE
Latest v7-commercial release (v7.4.11) is broken

### ISSUE THREAD

**Issue by watson** [hapijs/boom#282]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 10.24.1
* *module version with issue*: `@commercial/boom v7.4.11`
* *last module version without issue*: 
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): n/a
* *any other relevant information*: none

#### What are you trying to achieve or the steps to reproduce?

As of this writing, the `HEAD` of the `v7-commercial` branch has one dependency: `@commercial/hoek` ([source code](https://github.com/hapijs/boom/blob/cb085ad0f09b9e98d65d847f32833c3728f35b92/package.json#L18))
However, the code in `lib/index.js` tries to require `@hapi/hoek` ([source code](https://github.com/hapijs/boom/blob/cb085ad0f09b9e98d65d847f32833c3728f35b92/lib/index.js#L3)), which doesn't exist and as a result Node.js crashes.

When digging a little deeper, the [state of the repo at the 7.4.11 commit](https://github.com/hapijs/boom/tree/b2e97d2a6d0c72929a4648f082672c88d021b0ce) doesn't match the 7.4.11 release on npm. So something is also out of sync. You can see that if you `npm install @commercial/boom@7.4.11` locally and compare its `package.json` which the one in this repo.

#### What was the result you got?

Node.js crashes

#### What result did you expect?

Node.js shouldn't crash and the module should load and work as expected

**Comment by devinivy** [comment]
You may already be aware, but Eran is the only person who can resolve issues with the commercial packages 👍 CC @hueniverse for visibility.

**Comment by hueniverse** [comment]
I'm on it.
