### ISSUE TITLE
When returning Boom.badImplemention from an handler the isBoom property is not set on the request.response

### ISSUE THREAD

**Issue by marcpearson** [hapijs/boom#284]
Is it normal to not have property isBoom on the request.response when i returning Boom.badImplementation('My message here') from an Hapi handler function ?

**Comment by devinivy** [comment]
Hi Marc, could you please follow the issue template?  It seems you've deleted it, and I think it would have helped provide some more information required to look into the issue that you're experiencing.  I believe hapi [boomifies](https://hapi.dev/module/boom/api/?v=9.1.2#boomifyerr-options) all error responses, and that should set `isBoom` to `true` on the error.  If you're seeing something else happen, some details from the issue template and a reproduction would be a great step.  To start, here's an example showing things working as expected: https://runkit.com/60c18db503676e001ce17d66/60c18db5a4e11e001baefc09.
