### ISSUE TITLE
Extending Boom and unexpected instanceof behavior

### ISSUE THREAD

**Issue by wallacethefmh** [hapijs/boom#285]
#### Support plan

* *is this issue currently blocking your project?* no
* *is this issue affecting a production system?* no

#### Context

* *node version*: v14.17.1
* *module version*: 9.1.2
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*:

#### How can we help?

https://github.com/hapijs/boom/blob/80528a674af77703cb8d0be15b50a655225d5cae/lib/index.js#L92

Doesn't this code break the expected behavior of class hierarchy/polymorphism?

> const Boom = require('@hapi/boom').Boom;
undefined
> class A extends Boom{};
undefined
> class B extends A{};
undefined
> const a = new A();
undefined
> a instanceof B;
true

I see that removing that part of the Boom class doesn't fix the problem, since the Boom constructor actually returns a decorated Error and not an instance of itself. It's a bit strange.

It took me a while to figure out why instanceof for a subclass wasn't behaving like all other javascript classes, maybe it would just be worth adding something to the docs explaining the implications of extending Boom?

**Comment by kanongil** [comment]
Interesting. So the problem is that sub-classes inherit the `Symbol.hasInstance` method? I would not have guessed that.
