### ISSUE TITLE
Changelog for @hapi/boom 10.0.0

### ISSUE THREAD

**Issue by guyellis** [hapijs/boom#296]
#### Context

* *node version*: 16.x
* *module version*: 9.x

#### What are you trying to achieve or the steps to reproduce ?

```shell
npm i @hapi/boom@10
```

It appears that boom v10 is out. Please can you update the changelog: https://hapi.dev/module/boom/changelog/

**Comment by devinivy** [comment]
Thanks for noting!  There are going to be a lot of major releases this week, and the website may stay up to date along the way.  In the interim you can see the milestone for the v10 release for some details: https://github.com/hapijs/boom/milestone/68?closed=1

**Comment by Nargonath** [comment]
@guyellis Website is live with the latest releases. 😉 

![image](https://user-images.githubusercontent.com/583657/166327717-5be59d83-1d9b-4b33-92d2-96804ae6e64a.png)

**Comment by guyellis** [comment]
Thank you @devinivy @Nargonath 

For context, when our bot submits PRs for dependency upgrades we usually research the breaking changes (at a minimum) to ensure there's nothing scary in there which is why we need something like a changelog to help us.

**Comment by Nargonath** [comment]
Yes sure, that's the proper way of doing it I agree. It's just that we disabled automatic build on the website not to burn all our free credits on the hosting platform. It requires a manual update. As @devinivy mentioned if you need the changelog data at some point and the website is not updated yet, you can always go to GitHub => Issues => Milestones. We always link all the development to a specific milestone on GitHub and the website is actually pulling the data from there. 😉
