### ISSUE TITLE
missing 10.0.1 release at https://github.com/hapijs/boom/releases

### ISSUE THREAD

**Issue by DanielRuf** [hapijs/boom#301]
The latest release is not at https://github.com/hapijs/boom/releases but available as tag in the same section.

**Comment by Nargonath** [comment]
Thanks for reporting the missing release. Before we create it, you can find the issues for that milestones here: https://github.com/hapijs/boom/milestone/69?closed=1

**Comment by Nargonath** [comment]
New release is created. Thanks again.
