### ISSUE TITLE
Change of Dependency Name Breaks boom

### ISSUE THREAD

**Issue by bh-nextup** [hapijs/boom#306]
### Runtime

node.js

### Runtime version

>=14.0.0

### Module version

5.3.2

### Last module version without issue

5.3.1

### Used with

catbox

### Any other relevant information

Check the index.js file, and you'll see that you're referencing @commercial/hoek but you changed the dependency in the package.json to just hoek.

See this commit : [Commit](https://github.com/hapijs/boom/commit/5ad11fdd3f47c451daeae1836e4e3dd7970035e0)

See this file in that commit : [index.js](https://github.com/hapijs/boom/blob/5ad11fdd3f47c451daeae1836e4e3dd7970035e0/lib/index.js)

### What are you trying to achieve or the steps to reproduce?

When I launch the application, I get an error.

### What was the result you got?

Error: Cannot find module '@commercial/hoek'
Require stack:
- /srv/account/node_modules/catbox/node_modules/boom/lib/index.js

### What result did you expect?

I expected it to fine 'hoek' and not '@commercial/hoek'

**Comment by Nargonath** [comment]
Yes, you're right. That's my bad. I forgot to update the code. I'll publish a new version for it.

**Comment by Nargonath** [comment]
5.3.3 is published and should fix your issue.
