### ISSUE TITLE
What's the point of hiding the actual error from the user?

### ISSUE THREAD

**Issue by dciccale** [hapijs/boom#50]
I know that some errors should not be sent from the server to the client directly since it could be unsecure.. but let me explain my situation

when replying a Boom error, I always receive a 500 statuscode error with Internal Server Error message from the server,  if I can actually create Boom errors with custom messages, or prepending a custom message to the default one, how could I treat those errors which has different messages/codes in the client?

I have two layers of error handling in my server app. One layer is managed by a service which throw specific new error constructors with specific messages. 

in the second layer I have my controller where I reply things to the client, in that point depending of what type of error I get from the service I reply different Boom error type with custom or default message, something useful for displaying in the client, like a validation message, or the default unauthorized message, etc.

but since all errors are replying 500 and so on.. how could I manage this?

thanks

**Comment by Marsup** [comment]
Usually 500 errors are unexpected ones, you certainly don't want any of those errors leaking to your clients, that would be a security issue. You are probably not transforming those into appropriate boom errors.

**Comment by dciccale** [comment]
`server.js`
```javascript
var Hapi = require('hapi');
var Boom = require('boom');
var server = new Hapi.Server();
server.connection({port: '8888'});
server.route({
  method: 'GET',
  path: '/test',
  handler: function (request, reply) {
    var err = new Error('custom message');
    reply(Boom.wrap(err));
  }
});
server.start();
```

```bash
$ node server.js
```

```bash
$ curl http://localhost:8888/test
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

**Comment by Marsup** [comment]
Look at the documentation, it explicitly says that without any status code it defaults to 500.

**Comment by dciccale** [comment]
omg you are totally right
