### ISSUE TITLE
I can not push addition data of error to response

### ISSUE THREAD

**Issue by ondrasak** [hapijs/boom#54]
I want to create error that contains attr 'data' where I can push what i need

in documentation I've found method 'create'

> create(statusCode, [message], [data])

but the object what I've pushed to 'data' param I' have not found in response

**Comment by arb** [comment]
I'm not sure I understand the problem.
```js
var x = Boom.create(402, "Test", { foo: 'bar', name: 'adam' });
```
x is equal to
```
{ [Error: Test]
  data: { foo: 'bar', name: 'adam' },
  isBoom: true,
  isServer: false,
  output: 
   { statusCode: 402,
     payload: 
      { statusCode: 402,
        error: 'Payment Required',
        message: 'Test' },
     headers: {} },
  reformat: [Function] }
```

The `data` key is there and is what I passed in with `.create`.

**Comment by ondrasak** [comment]
I've supposed, the 'data' will be included also in 'output. payload' since I need to ship them to client (Browser app)

**Comment by arb** [comment]
https://github.com/hapijs/boom/issues/49 is how it's been solved in the past.

**Comment by ondrasak** [comment]
great :+1:
thanks
