### ISSUE TITLE
Question: Recommended way to add errorCode to errors

### ISSUE THREAD

**Issue by dschenkelman** [hapijs/boom#56]
First of all, great library really easy to use :smile:.

I'd like to see if you have any recommendations on how to have fixed error codes (i.e. `'invalid_connection'`) that are different from the error message. I'd would like to have a fixed set of those while being able to change error messages.

For example instead of the following `Boom.notFound('The user does not have an email')`:
```json
{
  "statusCode": 404,
  "message": "The user does not have an email",
  "error": "Not Found"
}
```

I'd would like to get something like this:
```json
{
  "statusCode": 404,
  "message": "The user does not have an email",
  "error": "Not Found",
  "errorCode": "user_without_email"
}
```

Is there some way to achieve something like this? If it requires a PR let me know and I can work on it (not saying that it should require a PR, just don't want to "ask for things").

**Comment by dschenkelman** [comment]
Is manipulating `error.output.payload` by adding the `errorCode` the way to go?

**Comment by arb** [comment]
Short answer - yes :+1: 

Long answer - Assuming you are using hapi, check [this](https://github.com/hapijs/hapi/blob/master/API.md#error-transformation) and [this](https://github.com/hapijs/boom/issues/49#issuecomment-90514349). I'm not going to change the `output` or `payload` values because they could have downstream impacts.

**Comment by dschenkelman** [comment]
Thanks!

**Comment by phated** [comment]
If you aren't plugin adverse, we've implemented this in [boomstick](https://www.npmjs.com/package/boomstick)

**Comment by AdriVanHoudt** [comment]
@phated thanks for the hint, I have something similar implemented but I think I'll implement some ideas from boomstick if I may ^^
