### ISSUE TITLE
how to wrap a mongoose validation error

### ISSUE THREAD

**Issue by dciccale** [hapijs/boom#64]
hi i am having an issue to reply a mongoose validation error.

this is the raw error

```
{ [ValidationError: User validation failed]
  message: 'User validation failed',
  name: 'ValidationError',
  errors: 
   { email: 
      { [ValidatorError: The specified email address is already in use.]
        properties: [Object],
        message: 'The specified email address is already in use.',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'email',
        value: 'test@test.com' } } }
```

but if I want to wrap the error for example on a `Boom.badData()` error I get only:

```
{
error: "Unprocessable Entity"
message: "User validation failed"
statusCode: 422
}
```

I also tried using `reply()` sending the raw error the way is returned from mongoose, but I am not able to specify the `.code(422)` it says method undefined. (it works if I send a string or an object, but not an error object).

so, is there any way to wrap this with Boom without loosing important fields of the error?

**Comment by AdriVanHoudt** [comment]
You can use https://github.com/hapijs/boom#createstatuscode-message-data and then send the important fields as `data` otherwise I would try https://github.com/hapijs/boom#wraperror-statuscode-message

**Comment by dciccale** [comment]
i am trying `reply(Boom.create(422, err.message, err));` however i'm still receiving the same thing on the browser or postman or network devtools whatever. where i am supposed to get that extra `data` ?

`wrap()` doesn't help, it does the same thing as create but without this extra `data`field

**Comment by dciccale** [comment]
also tried sending the `errors` object which is the most important thin `reply(Boom.create(422, err.message, err.errors));` but still getting the same basic payload

```
{
error: "Unprocessable Entity"
message: "User validation failed"
statusCode: 422
}
````

**Comment by arb** [comment]
@dciccale please see if [this](https://github.com/hapijs/boom#how-do-i-include-extra-information-in-my-responses-outputpayload-is-missing-data-what-gives) helps.

**Comment by dciccale** [comment]
@arb nope, that returns 

```
{
error: "Internal Server Error"
message: "An internal server error occurred"
statusCode: 500
}
```

i would prefer returning a `422` with at least the `errors` field from mongoose error.

**Comment by dciccale** [comment]
if I do this:

var e = Boom.whatever(err);

`e` looks something like this **before** going through `reply()`:

```
{ [Error: User validation failed]
  data: 
   { email: 
      { [ValidatorError: The specified email address is already in use.]
        properties: [Object],
        message: 'The specified email address is already in use.',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'email',
        value: 'test@test.com' } },
  isBoom: true,
  isServer: true,
  output: 
   { statusCode: 500,
     payload: 
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function],
  isDeveloperError: true }
```

the thing when passing this to the `reply()` method of hapi, i gues I should move this issue there

**Comment by arb** [comment]
You didn't read everything I linked to. You need to do error transformation if you want to expose more data to the client than is normally there. https://github.com/hapijs/hapi/blob/master/API.md#error-transformation

**Comment by dciccale** [comment]
@arb i'm really sorry, i finally solved it with that, really cool thx!

**Comment by dciccale** [comment]
and keep up with the good job guys, i'm never going back to express

**Comment by Kitanotori** [comment]
I wrapped the error simply this way:

```
			.catch(error => {
				const response = Boom.badRequest(error);
				response.output.payload.error = error;
				reply(response);
			});
```
