### ISSUE TITLE
Boom.notFound does not generate documented response payload

### ISSUE THREAD

**Issue by nroviw** [hapijs/boom#65]
With Hapi, running
`reply(Boom.notFound('missing'));`

Does not give expected response

    {
        "statusCode": 404,
        "error": "Not Found",
        "message": "missing"
    }

**Comment by mtharrison** [comment]
I suspect there's something wrong with your routing somewhere. Try this:

```javascript
var Hapi = require('hapi');
var Boom = require('boom');

var server = new Hapi.Server();
server.connection({ port: 4000 });

server.route({
    method: 'GET',
    path: '/',
    handler: function (request, reply) {

        reply(Boom.notFound('missing'));
    }
});

server.start(function (err) {

    if (err) {
        throw err;
    }
});
```

Works for me:

![screen shot 2015-08-17 at 11 55 29](https://cloud.githubusercontent.com/assets/916064/9303564/e10d8944-44d6-11e5-8052-6973b4aa0db9.png)

If you're still having issues, please post versions of hapi and boom.

**Comment by nroviw** [comment]
Verified that it works as you said. It seems to be broken when I used it inside a catch block for Thinky (rethinkDB ORM). I'll investigate further. Thanks for quick reply!
