### ISSUE TITLE
What happens to the 'data' sent?

### ISSUE THREAD

**Issue by luckysoni** [hapijs/boom#66]
Boom.badRequest('Invalid request', {name: 'required'});

Boom never returns the data passed to the function. It only returns the output.payload. What is the use of suppling data to Boom then? Should it not be returned in the response?

**Comment by arb** [comment]
Please see the FAQ found [here](https://github.com/hapijs/boom#how-do-i-include-extra-information-in-my-responses-outputpayload-is-missing-data-what-gives) as this question has been asked many times.

**Comment by luckysoni** [comment]
Thank you!
