### ISSUE TITLE
Error.captureStackTrace prevents Boom from being used in Safari

### ISSUE THREAD

**Issue by liamwooding** [hapijs/boom#72]
Hi, just ran into an issue with using a Browserified Boom - ```Error.captureStackTrace``` isn't supported in Safari, so we can't use it to wrap errors in the browser. I'll fork and attempt a fix.

**Comment by arb** [comment]
Please see the discussion on [this PR](https://github.com/hapijs/boom/pull/58). Boom isn't really intended for client side usage.
