### ISSUE TITLE
Custom message overrided by standard message

### ISSUE THREAD

**Issue by poliveira89** [hapijs/boom#73]
On every `Boom.badImplementation(err.message)` I was expecting a specific message but I only get this:
````json
{
  "statusCode":500,
  "error":"Internal Server Error",
  "message":"An internal server error occurred"
}
````

Even If I do `reply(Boom.badImplementation('damn'));`.

I will get the message before. And on the log I get the right message:
`151017/012509.439, [error], message: damn stack: Error: damn`

I'm using 2.8.0 version of this module.

**Comment by hueniverse** [comment]
Because you should not be telling your users how you fucked up. That's for you and your logs.

**Comment by poliveira89** [comment]
I understand that, but in some other frameworks I was able to choose if I want `DEBUG` mode active or not...

Thank you for your time and answer.

**Comment by devinivy** [comment]
@poliveira89 you could certainly write a plugin for use in development that replaces `err.message` onto `err.output.payload.message`.  It would essentially consist of an `onPreResponse` extension.  You may also find https://github.com/hapijs/tv useful for this type of debugging.

**Comment by poliveira89** [comment]
@devinivy thanks the TV module could be a great addition to my code! :+1:
