### ISSUE TITLE
I got an error when the first param is Chinese in Boom.unauthorized

### ISSUE THREAD

**Issue by ltfyxkfh** [hapijs/boom#76]
Boom.unauthorized('人', 'Token')
"message": "Uncaught error: Bad attribute value (人)"

**Comment by mtharrison** [comment]
As you're specifying `Token` auth scheme,  Boom is trying to put your message in a `WWW-Authenticate` header. 人 is not an allowed character for a header so it's failing.

I feel like you should be able to override the header message here using attributes, but this doesn't work:

    Boom.unauthorized('人', 'Token', { error: 'Something else' }

Maybe @arb has a better idea.

**Comment by arb** [comment]
I'm actually not sure what can be done here. The error message in a 401 needs to be something that can be put in a header. If you are trying to communicate '人' back to the client, there are other ways of doing that.

**Comment by devinivy** [comment]
You could provide a header-safe string as the message, then alter the payload to include the Chinese characters,
```js
var error = Boom.unauthorized('Expired', 'Token')
error.output.payload.message = '人';
```

**Comment by ltfyxkfh** [comment]
it worked,thx
