### ISSUE TITLE
badImplementation method message missing

### ISSUE THREAD

**Issue by bricss** [hapijs/boom#84]
Hi there,

I have updated _boom_ to the latest version and found that **badImplementation** method not returning custom messages anymore.

And I have looked in tests and found that test for message is also missing.

**Comment by johnbrett** [comment]
This is meant to happen, you don't want to expose internal errors to your users: https://github.com/hapijs/boom/issues/73

**Comment by bricss** [comment]
Ok, I thought so, but API docs confused me.
