### ISSUE TITLE
Strict mode error

### ISSUE THREAD

**Issue by rutaihwa** [hapijs/boom#87]
Through `hawk` for hapi, Im getting an error to `boom`. Im not sure if this issue is in the right place or I should post it in the `hawk`. The error log can be seen in the [ travis build](https://travis-ci.org/Infidive/apizen/jobs/93584071) and basically it complains about `SyntaxError: Use of const in strict mode`. How to fix this?

**Comment by rutaihwa** [comment]
I'll close this, because I think its a `hawk` issue not boom per se. But would be happy to get some ideas, if ever.

**Comment by arb** [comment]
The seems to be that you are using a pre 4.0.0 version of Node.

**Comment by rutaihwa** [comment]
That may explain why it works on my local machine. How do I make travis run with post 4.0.0 of node?

**Comment by gergoerdosi** [comment]
https://github.com/hapijs/boom/blob/master/.travis.yml#L3-L6

**Comment by rutaihwa** [comment]
Thanks @arb and @gergoerdosi !! :grinning: :+1:
