### ISSUE TITLE
how to set/update a cookie in combination with Boom?

### ISSUE THREAD

**Issue by santo74** [hapijs/boom#88]
When I return a regular json response from a route, I can set/update a cookie via Hapi's state() like this:

```
return reply({error:false, result:'all went well!'}).state('session', {user:'joe'});
```

When using Boom, however, this doesn't work:

```
return reply(Boom.badRequest('invalid api call')).state('session', {user:'joe', lastfailedrequest:Date.now()});
```
This results in the following error:
```
TypeError: reply(...).state is not a function
```

So how can I set/update a cookie when using Boom?

**Comment by hueniverse** [comment]
Try:

```js
reply.state(...);
reply(err);
```

**Comment by santo74** [comment]
Thanks Eran, that works indeed.
I do prefer a fluent api however, so is there a reason why this isn't the case with Boom?

**Comment by hueniverse** [comment]
Because you cannot decorate an error response.
