### ISSUE TITLE
Support for RFC 2324

### ISSUE THREAD

**Issue by andrewgoodchild** [hapijs/boom#90]
Can we please get support for 418 HTTP Status codes as described in RFC 2324 added to Boom?

I just really need to do a Boom.iAmATeapot()  ;-)

**Comment by hueniverse** [comment]
You do know that was an April's fool joke, right? :-)

**Comment by andrewgoodchild** [comment]
Yeah I know. I was just having some fun.

**Comment by AdriVanHoudt** [comment]
there was a PR for it ;) https://github.com/hapijs/boom/pull/78

**Comment by bisubus** [comment]
@hueniverse RFCs aren't reasons for jokes. Can we reconsider it, please?

`Boom.create(418)` is barely readable, to the point where it can be considered an tea-pottern.
