### ISSUE TITLE
status code 418

### ISSUE THREAD

**Issue by ADumaine** [hapijs/boom#96]
Why does 418 in lib\index.js use backticks instead of quotes?

It causes uglifyjs to choke since uglifyjs does not yet support ES6.

Shouldn't 418 use quotes for consistency?

**Comment by gergoerdosi** [comment]
Probably because of the single quote in the value. But I agree, it's better to use single quotes for consistency, so submitted a PR.

Anyway, why do you uglify the code? This module targets node 4+ which supports template strings.

**Comment by ADumaine** [comment]
To accommodate the single quotes I guess the `I'm` could be changed to `I
am`.

I'm in the middle of updating a just completed project built in react 13 to
react 14 and started with a prebuilt account management module that used
uglify for compression.  I am just trying to get it to work with the
upgrades before pulling out or changing functionality.

Thanks for the quick response!


Allan Dumaine
480 342-9045

**Comment by Marsup** [comment]
How is boom related to any of that ?

**Comment by gergoerdosi** [comment]
RFC 2324 defines it as "I'm a teapot", so I wouldn't change it to "I am".

https://tools.ietf.org/html/rfc2324#section-2.3.2

**Comment by ADumaine** [comment]
Started the project with https://github.com/jedireza/aqua which uses it.

Allan Dumaine
480 342-9045

**Comment by ADumaine** [comment]
Then double quotes should do it.

Allan Dumaine
480 342-9045

**Comment by Marsup** [comment]
I don't see why boom would be of any use on the front end, exclude it from your build.

**Comment by arb** [comment]
Boom is for node >= 4. I used back ticks to avoid the annoying escape character.

**Comment by hueniverse** [comment]
I think we need a style rule on that. You are using it as a backdoor to using `"` :-)
